FROM app:base

# Bundle install
WORKDIR /srv
COPY Gemfile /srv/Gemfile
COPY Gemfile.lock /srv/Gemfile.lock
RUN ~/.rbenv/shims/bundle install

COPY . /srv

CMD ["bash", "-c", "bundle exec rake assets:precompile && bundle exec rake db:migrate && bundle exec rails server -b 0.0.0.0"]
